"""Levista_Performance_Report.xlsx — the 25-sheet executive workbook.

Layout follows the existing July workbook: a title row, then one block per coffee
category (Instant / Filter / Cold), each with its own header row and a subtotal.
Columns are declared once per entity type; any column with no data for a given
platform is dropped rather than printed as a column of blanks.

Note on pivots: openpyxl cannot create a native Excel PivotTable cache. These
sheets are pre-aggregated, formatted, filterable summary tables — the same thing
the hand-built July workbook contained.
"""
from __future__ import annotations

from datetime import date
from pathlib import Path

import pandas as pd
from openpyxl import Workbook
from openpyxl.drawing.image import Image as XLImage
from openpyxl.formatting.rule import CellIsRule
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

import config
from analytics import insights as ai
from analytics import metrics
from db.models import alerts, anomalies, get_engine, recommendations, uploaded_files

# ---------------------------------------------------------------- styling
BRAND = "1F3B4D"
ACCENT = "6F4E37"          # coffee brown
GREEN, AMBER, RED = "C6EFCE", "FFEB9C", "FFC7CE"
GREEN_T, AMBER_T, RED_T = "006100", "9C6500", "9C0006"

TITLE_FONT = Font(size=16, bold=True, color="FFFFFF")
TITLE_FILL = PatternFill("solid", fgColor=BRAND)
BLOCK_FONT = Font(size=11, bold=True, color="FFFFFF")
BLOCK_FILL = PatternFill("solid", fgColor=ACCENT)
HEAD_FONT = Font(size=10, bold=True, color="FFFFFF")
HEAD_FILL = PatternFill("solid", fgColor="4A6572")
TOTAL_FONT = Font(size=10, bold=True)
TOTAL_FILL = PatternFill("solid", fgColor="E8EDF0")
NOTE_FONT = Font(size=10, italic=True, color="9C0006")
THIN = Side(style="thin", color="D0D7DC")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)

ASSETS = Path(__file__).resolve().parent.parent / "assets"
LOGO_WHITE = ASSETS / "levista_logo_white.png"   # the title row is dark navy

MONEY = '₹#,##0'
MONEY2 = '₹#,##0.00'
INT = '#,##0'
PCT = '0.00%'
NUM2 = '0.00'

FORMATS = {
    "impressions": INT, "clicks": INT, "orders": INT, "units": INT, "atc": INT,
    "new_users": INT,
 "spend": MONEY, "revenue": MONEY, "budget": MONEY,
    "cpc": MONEY2, "cpm": MONEY2, "ctr": PCT, "conv_rate": PCT, "roas": NUM2,
    "revenue_share": PCT, "spend_share": PCT, "clicks_coverage": PCT,
    "revenue_growth": PCT, "spend_growth": PCT, "orders_growth": PCT, "roas_change": NUM2,
    "impact_value": MONEY, "value": MONEY, "z_score": NUM2, "cohort_mean": NUM2,
}
SUMMABLE = {"impressions", "clicks", "orders", "units", "atc", "new_users",
            "spend", "revenue", "budget"}

# Column spec per entity type. Empty columns are dropped per platform, so one
# spec covers every platform's variant of the same report.
COLUMNS = {
    # Exactly the columns Levista's report specifies, in the order specified. Anything
    # a platform does not supply is dropped per block rather than printed empty, so a
    # sheet never shows a column of dashes.
    "campaign": [("Campaign Name", "campaign_name"), ("Impressions", "impressions"),
                 ("Clicks", "clicks"), ("Spends", "spend"), ("Orders", "orders"),
                 ("Revenue", "revenue"), ("ROAS", "roas"), ("CPM", "cpm"),
                 ("CPC", "cpc"), ("CTR", "ctr"), ("ATC", "atc"),
                 ("New to brand(purchase)", "new_users")],
    "product": [("Product ID", "product_id"), ("Product Name", "product_name"),
                ("Impressions", "impressions"), ("Clicks", "clicks"),
                ("Ad Spend", "spend"), ("Units Sold", "units"),
                ("Add to Cart", "atc"), ("Revenue", "revenue"), ("ROAS", "roas"),
                ("CPM", "cpm"), ("CPC", "cpc"), ("CTR", "ctr")],
    "city": [("City Name", "city"), ("Impressions", "impressions"),
             ("Clicks", "clicks"), ("Spend", "spend"), ("Orders", "orders"),
             ("Add to Cart", "atc"), ("Revenue", "revenue"), ("ROAS", "roas"),
             ("CPM", "cpm"), ("CPC", "cpc"), ("CTR", "ctr")],
    "keyword": [("Campaign Name", "campaign_name"), ("Keywords", "keyword"),
                ("Match Type", "match_type"), ("Impression", "impressions"),
                ("Clicks", "clicks"), ("Spend", "spend"), ("Order", "orders"),
                ("Add to Cart", "atc"), ("Revenue", "revenue"), ("ROAS", "roas"),
                ("CPM", "cpm"), ("CPC", "cpc"), ("CTR", "ctr"),
                ("New Users", "new_users")],
}

# Plain-English glossary shown beside the KPIs — the audience is category and
# brand managers, not analysts.
GLOSSARY = [
    ("Spend", "Money paid to the platform for advertising."),
    ("Revenue", "Sales value generated by those ads."),
    ("ROAS", "Revenue ÷ Ad Spend. ₹4.00 means every ₹1 spent brought back ₹4."),
    ("ROI", "(Revenue − Spend) ÷ Spend. The profit on top of what was spent."),
    ("Orders", "Number of purchases the ads generated."),
    ("CTR", "Click-Through Rate: how often people who saw an ad clicked it."),
    ("CPC", "Cost Per Click: what one click costs on average."),
    ("CPM", "Cost per 1,000 times the ad was shown."),
    ("Conversion Rate", "Share of clicks that turned into an order."),
    ("Add to Cart", "Shoppers who added the product to their basket."),
]


def _fit(ws, widths: dict):
    for idx, width in widths.items():
        ws.column_dimensions[get_column_letter(idx)].width = width


def _title(ws, title: str, period: tuple, span: int = 12) -> int:
    start, end = period
    ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=max(span, 4))
    cell = ws.cell(row=1, column=1, value=title)
    cell.font, cell.fill = TITLE_FONT, TITLE_FILL
    # Indent past the floated logo. Character units, not spaces — column A's width
    # differs per sheet, so a fixed run of spaces would land differently each time.
    cell.alignment = Alignment(vertical="center", indent=11)
    ws.row_dimensions[1].height = 34
    if LOGO_WHITE.exists():
        # Floated over the dark title fill, so it needs the white variant.
        logo = XLImage(str(LOGO_WHITE))
        logo.height = 22
        logo.width = int(22 * 3713 / 1073)
        ws.add_image(logo, "A1")
    label = (f"Reporting period: {start:%d %b %Y} – {end:%d %b %Y}"
             if start and end else "Reporting period: not stated in source files")
    ws.cell(row=2, column=1, value=label).font = Font(size=9, italic=True, color="55606A")
    return 4


def _no_data(ws, row: int, what: str) -> int:
    ws.cell(row=row, column=1,
            value=f"No source data — {what}. Fetch the export and re-run the pipeline "
                  "to populate this sheet.").font = NOTE_FONT
    return row + 2


def _visible_columns(df: pd.DataFrame, spec: list) -> list:
    """Drop spec columns absent or entirely empty for this slice of data."""
    out = []
    for header, field in spec:
        if field in df.columns and df[field].notna().any():
            out.append((header, field))
    return out


def _write_table(ws, row: int, df: pd.DataFrame, spec: list, block_title: str | None,
                 total_label: str = "Total") -> int:
    columns = _visible_columns(df, spec)
    if not columns:
        return row
    width = len(columns)

    if block_title:
        ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=width)
        cell = ws.cell(row=row, column=1, value=block_title)
        cell.font, cell.fill = BLOCK_FONT, BLOCK_FILL
        row += 1

    header_row = row
    for col, (header, _) in enumerate(columns, start=1):
        cell = ws.cell(row=row, column=col, value=header)
        cell.font, cell.fill, cell.border = HEAD_FONT, HEAD_FILL, BORDER
        cell.alignment = Alignment(horizontal="center", wrap_text=True)
    row += 1

    first_data = row
    for _, record in df.iterrows():
        for col, (_, field) in enumerate(columns, start=1):
            value = record.get(field)
            if pd.isna(value):
                value = None
            cell = ws.cell(row=row, column=col, value=value)
            cell.border = BORDER
            if field in FORMATS:
                cell.number_format = FORMATS[field]
        row += 1
    last_data = row - 1

    # Subtotal: sums for volumes, recomputed ratios (never an average of ratios).
    totals = {f: pd.to_numeric(df[f], errors="coerce").sum()
              for _, f in columns if f in SUMMABLE and f in df.columns}
    for col, (_, field) in enumerate(columns, start=1):
        cell = ws.cell(row=row, column=col)
        cell.font, cell.fill, cell.border = TOTAL_FONT, TOTAL_FILL, BORDER
        if col == 1:
            cell.value = total_label
        elif field in totals:
            cell.value = totals[field]
            cell.number_format = FORMATS.get(field, INT)
        elif field == "roas" and totals.get("spend"):
            cell.value = totals.get("revenue", 0) / totals["spend"]
            cell.number_format = NUM2
        elif field == "ctr" and totals.get("impressions"):
            cell.value = totals.get("clicks", 0) / totals["impressions"]
            cell.number_format = PCT
        elif field == "cpc" and totals.get("clicks"):
            cell.value = totals["spend"] / totals["clicks"]
            cell.number_format = MONEY2
        elif field == "conv_rate" and totals.get("clicks"):
            cell.value = totals.get("orders", 0) / totals["clicks"]
            cell.number_format = PCT
    row += 2

    _traffic_light(ws, columns, first_data, last_data)
    _fit(ws, {i: (42 if f in ("campaign_name", "product_name", "keyword") else 14)
              for i, (_, f) in enumerate(columns, start=1)})
    return row, header_row


def _traffic_light(ws, columns, first: int, last: int):
    """Green above healthy ROAS, amber above break-even, red below it."""
    if last < first:
        return
    for col, (_, field) in enumerate(columns, start=1):
        if field != "roas":
            continue
        letter = get_column_letter(col)
        span = f"{letter}{first}:{letter}{last}"
        ws.conditional_formatting.add(span, CellIsRule(
            operator="greaterThanOrEqual", formula=[str(config.HEALTHY_ROAS)],
            fill=PatternFill("solid", fgColor=GREEN), font=Font(color=GREEN_T)))
        ws.conditional_formatting.add(span, CellIsRule(
            operator="between", formula=[str(config.BREAKEVEN_ROAS), str(config.HEALTHY_ROAS)],
            fill=PatternFill("solid", fgColor=AMBER), font=Font(color=AMBER_T)))
        ws.conditional_formatting.add(span, CellIsRule(
            operator="lessThan", formula=[str(config.BREAKEVEN_ROAS)],
            fill=PatternFill("solid", fgColor=RED), font=Font(color=RED_T)))


def _category_sheet(wb, name: str, title: str, df: pd.DataFrame, entity: str,
                    period: tuple, missing_note: str):
    """One sheet, one block per coffee category, per the July workbook layout."""
    ws = wb.create_sheet(name[:31])
    row = _title(ws, title, period)
    if df.empty:
        _no_data(ws, row, missing_note)
        return ws

    spec = COLUMNS[entity]
    first_header = None
    for category in metrics.categories_for(df):
        block = df[df["category"] == category] if category else df[df["category"].isna()]
        if block.empty:
            continue
        block = metrics.collapse(block.copy(), entity)
        label = category or "Uncategorised"
        row, header_row = _write_table(ws, row, block, spec, label,
                                       total_label=f"{label} total")
        first_header = first_header or header_row
    if first_header:
        ws.freeze_panes = ws.cell(row=first_header + 1, column=1)
    return ws


# ---------------------------------------------------------------- sheets

def _executive_summary(wb, engine, period):
    ws = wb.create_sheet("Executive Summary")
    row = _title(ws, "Executive Summary", period, span=8)
    kpis = metrics.overall_kpis(engine)
    if not kpis:
        _no_data(ws, row, "no data was loaded")
        return

    cards = [
        ("Total Revenue", kpis["revenue"], MONEY),
        ("Total Ad Spend", kpis["spend"], MONEY),
        ("ROAS", kpis["roas"], NUM2),
        ("ROI", kpis["roi"], PCT),
        ("Orders", kpis["orders"], INT),
        ("Conversion Rate", kpis["conv_rate"], PCT),
    ]
    for i, (label, value, fmt) in enumerate(cards):
        col = 1 + i * 2
        ws.merge_cells(start_row=row, start_column=col, end_row=row, end_column=col + 1)
        head = ws.cell(row=row, column=col, value=label)
        head.font, head.fill = Font(size=9, bold=True, color="FFFFFF"), PatternFill("solid", fgColor="4A6572")
        head.alignment = Alignment(horizontal="center")
        ws.merge_cells(start_row=row + 1, start_column=col, end_row=row + 1, end_column=col + 1)
        cell = ws.cell(row=row + 1, column=col, value=None if value is None or pd.isna(value) else value)
        cell.font = Font(size=14, bold=True, color=BRAND)
        cell.alignment = Alignment(horizontal="center")
        cell.number_format = fmt
        cell.fill = PatternFill("solid", fgColor="F2F5F7")
    ws.row_dimensions[row + 1].height = 24
    row += 3

    table = metrics.platform_comparison(engine)
    row, header_row = _write_table(
        ws, row, table,
        [("Platform", "platform"), ("Revenue", "revenue"), ("Spend", "spend"),
         ("Orders", "orders"), ("ROAS", "roas"), ("CTR", "ctr"),
         ("Conv. Rate", "conv_rate"), ("Revenue Share", "revenue_share")],
        "Platform performance, best revenue first", total_label="All platforms")

    ws.cell(row=row, column=1, value="What happened, and what to do about it").font = \
        Font(size=12, bold=True, color=BRAND)
    row += 1
    narrative = ai.load(engine, __import__("db.models", fromlist=["insights"]).insights)
    for _, item in narrative.iterrows():
        ws.cell(row=row, column=1, value=item["platform"]).font = Font(bold=True, size=11)
        row += 1
        for heading, field in (("What happened", "what_happened"),
                               ("Why", "why_it_happened"),
                               ("What to do next", "what_to_do_next")):
            ws.cell(row=row, column=1, value=heading).font = Font(bold=True, size=9, color="55606A")
            ws.merge_cells(start_row=row, start_column=2, end_row=row, end_column=9)
            cell = ws.cell(row=row, column=2, value=item[field])
            cell.alignment = Alignment(wrap_text=True, vertical="top")
            ws.row_dimensions[row].height = 30
            row += 1
        row += 1

    ws.cell(row=row, column=1, value="What the numbers mean").font = Font(size=12, bold=True, color=BRAND)
    row += 1
    for term, meaning in GLOSSARY:
        ws.cell(row=row, column=1, value=term).font = Font(bold=True, size=9)
        ws.merge_cells(start_row=row, start_column=2, end_row=row, end_column=9)
        ws.cell(row=row, column=2, value=meaning).font = Font(size=9)
        row += 1
    _fit(ws, {1: 20, 2: 26, 3: 16, 4: 14, 5: 14, 6: 14, 7: 14, 8: 14, 9: 16})


def _comparison_sheet(wb, name: str, title: str, df: pd.DataFrame, spec: list,
                      period: tuple, missing_note: str, top: int = 60):
    ws = wb.create_sheet(name[:31])
    row = _title(ws, title, period, span=len(spec))
    if df.empty:
        _no_data(ws, row, missing_note)
        return
    df = df.sort_values("revenue", ascending=False, na_position="last").head(top)
    row, header_row = _write_table(ws, row, df, spec, None, total_label="Total (shown rows)")
    ws.freeze_panes = ws.cell(row=header_row + 1, column=1)
    ws.auto_filter.ref = f"A{header_row}:{get_column_letter(len(_visible_columns(df, spec)))}{header_row}"


def _recommendations_sheet(wb, engine, period):
    ws = wb.create_sheet("Recommendations")
    row = _title(ws, "Recommendations", period, span=6)
    df = ai.load(engine, recommendations)
    if df.empty:
        _no_data(ws, row, "no recommendations were generated")
        return
    df["_order"] = df["priority"].map(ai.PRIORITY_ORDER).fillna(9)
    df = df.sort_values(["_order", "impact_value"], ascending=[True, False])
    row, header_row = _write_table(
        ws, row, df,
        [("Priority", "priority"), ("Platform", "platform"), ("Type", "entity_type"),
         ("Name", "entity_name"), ("Action", "action"),
         ("Money at stake", "impact_value"), ("Why", "rationale")],
        None, total_label="")
    ws.freeze_panes = ws.cell(row=header_row + 1, column=1)
    ws.auto_filter.ref = f"A{header_row}:G{header_row}"
    _fit(ws, {1: 10, 2: 12, 3: 11, 4: 40, 5: 16, 6: 16, 7: 80})
    for r in range(header_row + 1, ws.max_row + 1):
        ws.cell(row=r, column=7).alignment = Alignment(wrap_text=True, vertical="top")
    ws.conditional_formatting.add(
        f"A{header_row + 1}:A{ws.max_row}",
        CellIsRule(operator="equal", formula=['"High"'],
                   fill=PatternFill("solid", fgColor=RED), font=Font(color=RED_T, bold=True)))
    ws.conditional_formatting.add(
        f"A{header_row + 1}:A{ws.max_row}",
        CellIsRule(operator="equal", formula=['"Medium"'],
                   fill=PatternFill("solid", fgColor=AMBER), font=Font(color=AMBER_T)))


def _alerts_sheet(wb, engine, period):
    ws = wb.create_sheet("Alerts & Anomalies")
    row = _title(ws, "Alerts & Anomalies", period, span=6)
    alert_df = ai.load(engine, alerts)
    if alert_df.empty:
        row = _no_data(ws, row, "no alerts were raised")
    else:
        alert_df["_order"] = alert_df["severity"].map(ai.PRIORITY_ORDER).fillna(9)
        alert_df = alert_df.sort_values("_order")
        row, header = _write_table(
            ws, row, alert_df,
            [("Severity", "severity"), ("Platform", "platform"), ("Type", "alert_type"),
             ("What", "entity_name"), ("Detail", "message")],
            "Alerts", total_label="")
        ws.conditional_formatting.add(
            f"A{header + 1}:A{row}",
            CellIsRule(operator="equal", formula=['"High"'],
                       fill=PatternFill("solid", fgColor=RED), font=Font(color=RED_T, bold=True)))

    anomaly_df = ai.load(engine, anomalies)
    if anomaly_df.empty:
        _no_data(ws, row, "no anomalies were detected")
    else:
        anomaly_df = anomaly_df.reindex(
            anomaly_df["z_score"].abs().sort_values(ascending=False).index)
        _write_table(ws, row, anomaly_df,
                     [("Platform", "platform"), ("Type", "entity_type"), ("Name", "entity_name"),
                      ("Measure", "metric"), ("Value", "value"), ("Typical", "cohort_mean"),
                      ("Std deviations", "z_score"), ("Direction", "direction")],
                     "Anomalies — unusually far from the norm for that platform",
                     total_label="")
    _fit(ws, {1: 12, 2: 14, 3: 16, 4: 34, 5: 90})


def _raw_summary_sheet(wb, engine, period):
    ws = wb.create_sheet("Raw Data Summary")
    row = _title(ws, "Raw Data Summary — every file the pipeline saw", period, span=8)
    with engine.connect() as conn:
        df = pd.read_sql(uploaded_files.select(), conn)
    if df.empty:
        _no_data(ws, row, "no files were processed")
        return
    df = df.sort_values(["processing_status", "platform", "filename"])
    row, header_row = _write_table(
        ws, row, df,
        [("File", "filename"), ("Platform", "platform"), ("Sub-platform", "sub_platform"),
         ("Report type", "report_type"), ("Sheet", "sheet_name"), ("Category", "category"),
         ("Rows", "row_count"), ("Status", "processing_status"), ("Note", "error")],
        None, total_label="Total rows")
    ws.freeze_panes = ws.cell(row=header_row + 1, column=1)
    ws.auto_filter.ref = f"A{header_row}:I{header_row}"
    _fit(ws, {1: 58, 2: 12, 3: 14, 4: 13, 5: 20, 6: 15, 7: 8, 8: 14, 9: 60})


# ---------------------------------------------------------------- entry point

# Every platform gets each report type it can produce, in the order Levista's spec
# lists them. Campaign first: it is the platform's full billed total, and four
# platforms previously had no campaign sheet at all, so an uploaded campaign report
# appeared only in the cross-platform sheet.
PLATFORM_SHEETS = {
    "Amazon":    ["campaign", "product", "keyword"],
    "Flipkart":  ["campaign", "product", "keyword"],
    # Only Instamart and Zepto report a city dimension.
    "Instamart": ["campaign", "product", "city", "keyword"],
    "Zepto":     ["campaign", "product", "city", "keyword"],
    "BigBasket": ["campaign", "product", "keyword"],
    "Blinkit":   ["campaign", "product", "keyword"],
}

SHEET_PLAN = [
    (f"{platform} {entity.capitalize()} Report", platform, entity,
     f"no {platform} {entity} report in the input folder")
    for platform, entities in PLATFORM_SHEETS.items()
    for entity in entities
]

FETCHERS = {"product": metrics.products, "keyword": metrics.keywords,
            "city": metrics.cities, "campaign": metrics.campaigns}


def build(engine=None, path=None, period_label=None):
    engine = engine or get_engine()
    period_label = period_label or metrics.latest_period(engine)
    prior = metrics.prior_period(engine, period_label)
    period = metrics.reporting_period(engine, period_label)
    # Say so in the header when the two months are different lengths, rather than
    # letting a per-day figure be read as a total.
    days = metrics.period_days(engine, period_label)
    prior_days = metrics.period_days(engine, prior) if prior else None
    uneven = bool(days and prior_days and abs(days - prior_days) / max(days, prior_days) > 0.05)
    growth_suffix = f" per day vs {prior}" if uneven else (f" vs {prior}" if prior else "")
    wb = Workbook()
    wb.remove(wb.active)

    _executive_summary(wb, engine, period)

    campaigns_all = metrics.campaigns(engine)
    _comparison_sheet(wb, "Overall Campaign Performance",
                      "Overall Campaign Performance — every platform",
                      campaigns_all,
                      [("Platform", "platform"), ("Sub-platform", "sub_platform")]
                      + COLUMNS["campaign"],
                      period, "no campaign data was loaded", top=200)

    for name, platform, entity, note in SHEET_PLAN:
        df = FETCHERS[entity](engine, platform=platform)
        _category_sheet(wb, name, f"{name}", df, entity, period, note)

    _comparison_sheet(wb, "Platform Comparison", "Platform Comparison",
                      metrics.platform_comparison(engine),
                      [("Platform", "platform"), ("Revenue", "revenue"), ("Spend", "spend"),
                       ("Orders", "orders"), ("Impressions", "impressions"),
                       ("Clicks", "clicks"), ("ROAS", "roas"), ("CTR", "ctr"),
                       ("CPC", "cpc"), ("Conv. Rate", "conv_rate"),
                       ("Revenue Share", "revenue_share"), ("Spend Share", "spend_share"),
                       ("Revenue Rank", "rank_revenue")]
                      + ([(f"Revenue Growth{growth_suffix}", "revenue_growth"),
                          (f"Spend Growth{growth_suffix}", "spend_growth"),
                          ("ROAS Change", "roas_change")] if prior else []),
                      period, "no platform data was loaded", top=50)

    _comparison_sheet(wb, "Product Comparison", "Product Comparison — across platforms",
                      metrics.collapse(metrics.products(engine), "product", ["platform"]),
                      [("Platform", "platform"), ("Category", "category")] + COLUMNS["product"],
                      period, "no product reports were found", top=120)
    _comparison_sheet(wb, "Keyword Comparison", "Keyword Comparison — across platforms",
                      metrics.collapse(metrics.keywords(engine), "keyword", ["platform"]),
                      [("Platform", "platform"), ("Category", "category")] + COLUMNS["keyword"],
                      period, "no keyword reports were found", top=150)
    _comparison_sheet(wb, "City Comparison", "City Comparison — across platforms",
                      metrics.collapse(metrics.cities(engine), "city", ["platform"]),
                      [("Platform", "platform"), ("Category", "category")] + COLUMNS["city"],
                      period, "no city reports were found", top=150)

    _recommendations_sheet(wb, engine, period)
    _alerts_sheet(wb, engine, period)
    _raw_summary_sheet(wb, engine, period)

    path = path or (config.OUTPUT_DIR / "Levista_Performance_Report.xlsx")
    path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(path)
    return path, len(wb.sheetnames)


if __name__ == "__main__":
    out, sheets = build()
    print(f"Wrote {out} ({sheets} sheets)")
